export const INTERNAL_STATES = [
    {
        id: 'dnd_simulator',
        name: 'DnD Simulator',
        icon: '🐉',
        description: 'Dice, skills, and character-driven simulation of in-world actions.',
        defaultEnabled: true,
    },
    {
        id: 'internal_agenda',
        name: 'Internal Agenda',
        icon: '📅',
        description: 'Tracks each character\'s goals, plans, and shifting priorities.',
        defaultEnabled: true,
    },
    {
        id: 'gm_notebook',
        name: 'GM\'s Notebook',
        icon: '📒',
        description: 'Keeps running notes on the scene, NPCs, locations, and open plot threads.',
        defaultEnabled: true,
    },
    {
        id: 'inventory',
        name: 'Inventory, Feats, Titles',
        icon: '🗡️',
        description: 'Tracks items, equipment, feats, and earned titles per character.',
        defaultEnabled: true,
    },
    {
        id: 'relationships',
        name: 'Relationships RPG',
        icon: '🥰',
        description: 'Models bonds, trust, and relationship dynamics between characters.',
        defaultEnabled: true,
    },
    {
        id: 'world_sim',
        name: 'World Sim',
        icon: '🌎',
        description: 'Simulates world state, factions, and consequences beyond the immediate scene.',
        defaultEnabled: true,
    },
    {
        id: 'chekhovs_gun',
        name: 'Chekhov\'s Gun',
        icon: '🔫',
        description: 'Records planted details and promises so they pay off later.',
        defaultEnabled: true,
    },
    {
        id: 'internal_thoughts',
        name: 'Internal Thoughts',
        icon: '🧠',
        description: 'Renders each character\'s private thoughts and unfiltered reactions.',
        defaultEnabled: true,
    },
    {
        id: 'master',
        name: 'Internal States (Master)',
        icon: '👾',
        description: 'The master block that orchestrates all enabled Internal States modules.',
        defaultEnabled: true,
    },
];
